PRÁCTICA 2 - EJERCICIO 1

In [323]:
import pandas as pd
import numpy as np
np.random.seed(10)
from matplotlib import pyplot as plt
import csv

Creamos la tabla para el caso de la puerta lógica AND

In [324]:
df = pd.DataFrame(columns=['Epoch','Entrada_X1', 'Entrada_X2','Yd','Wi1', 'Wi2','Yr','Error','Wf1', 'Wf2'])
df

Empty DataFrame
Columns: [Epoch, Entrada_X1, Entrada_X2, Yd, Wi1, Wi2, Yr, Error, Wf1, Wf2]
Index: []

Para el proceso de entrenamiento:
1. Pesos W generados aleatoriamente
2. Introduccion de una entrada
3. Se calcula el error
4. Error = 0: volver al paso 2. con una nueva entrada
5. Se inicializa ∆Wi= 0
6. Se aplica la Ley de Hebb
7. Se actualizan los pesos
8. Volver al paso 2. con una nueva entrada

In [325]:
# 1.Pesos generados automáticamente:
pesos = np.random.uniform(-1, 1, size=(1, 2))

In [326]:
pesos

array([[ 0.54264129, -0.9584961 ]])

In [327]:
def entrenamientoPerceptron(datosEntrada,pesos,umbral,lr):
  contadorIteraciones = 0
  contadorEpoch = 1
  ErrorBool = False
  while(ErrorBool == False and contadorIteraciones < 4000):
    cont = 0
    contError = 0
    for dato in datosEntrada:
      X1 = dato[0] #Entrada 1
      X2 = dato[1] #Entrada 2
      Yd = dato[2] #Salida Esperada
      Wi1 = pesos[0][0]
      Wi1 = np.round(Wi1,2)
      Wi2 = pesos[0][1]
      Wi2 = np.round(Wi2,2)

      # S = entrada de la neurona, necesaria para calcular la salida real: Yr
      
      S = X1 * pesos[0][0] + X2 * pesos[0][1]
      
      if (S >= umbral):
        Yr = 1
      else:
        Yr = 0
      Error = Yd - Yr
      #Error.append(Yd - Yr)
      if Error == 0:
        contError+=1
      # Reajuste de los pesos:
      W1 = pesos[0][0] + lr*Error*X1
      W2 = pesos[0][1] + lr*Error*X2
      # Redondeamos el valor de los pesos
      W1 = np.round(W1,2)
      W2 = np.round(W2,2)
      # Actualizacion de los pesos
      pesos[0][0] = W1
      pesos[0][1] = W2

      df.loc[contadorIteraciones] = contadorEpoch, X1, X2, Yd, Wi1, Wi2, Yr, Error, W1, W2
      contadorIteraciones+=1
      cont+=1
    if contError == 4:
      ErrorBool = True
    contadorEpoch+=1
    # if (Error[0] == 0) & (Error[1] == 0) & (Error[2] == 0) & (Error[3] == 0):
    #   ErrorBool = True

In [328]:
puertaAND = [(0,0,0),(0,1,0),(1,0,0),(1,1,1)]
lr = 0.8
umbral = 1
entrenamientoPerceptron(puertaAND, pesos, umbral, lr)

In [329]:
df

    Epoch  Entrada_X1  Entrada_X2   Yd   Wi1   Wi2   Yr  Error   Wf1   Wf2
0     1.0         0.0         0.0  0.0  0.54 -0.96  0.0    0.0  0.54 -0.96
1     1.0         0.0         1.0  0.0  0.54 -0.96  0.0    0.0  0.54 -0.96
2     1.0         1.0         0.0  0.0  0.54 -0.96  0.0    0.0  0.54 -0.96
3     1.0         1.0         1.0  1.0  0.54 -0.96  0.0    1.0  1.34 -0.16
4     2.0         0.0         0.0  0.0  1.34 -0.16  0.0    0.0  1.34 -0.16
5     2.0         0.0         1.0  0.0  1.34 -0.16  0.0    0.0  1.34 -0.16
6     2.0         1.0         0.0  0.0  1.34 -0.16  1.0   -1.0  0.54 -0.16
7     2.0         1.0         1.0  1.0  0.54 -0.16  0.0    1.0  1.34  0.64
8     3.0         0.0         0.0  0.0  1.34  0.64  0.0    0.0  1.34  0.64
9     3.0         0.0         1.0  0.0  1.34  0.64  0.0    0.0  1.34  0.64
10    3.0         1.0         0.0  0.0  1.34  0.64  1.0   -1.0  0.54  0.64
11    3.0         1.0         1.0  1.0  0.54  0.64  1.0    0.0  0.54  0.64
12    4.0         0.0         0.0  0.0  0.54  0.64  0.0    0.0  0.54  0.64
13    4.0         0.0         1.0  0.0  0.54  0.64  0.0    0.0  0.54  0.64
14    4.0         1.0         0.0  0.0  0.54  0.64  0.0    0.0  0.54  0.64
15    4.0         1.0         1.0  1.0  0.54  0.64  1.0    0.0  0.54  0.64

In [330]:
df.to_csv('L2P1-Perceptron.csv', index=False)

In [331]:
pesos = np.random.uniform(-1, 1, size=(1, 2))
lr = 0.6
umbral = 0.9
puertaXOR = [(0,0,0),(0,1,1),(1,0,1),(1,1,0)]
entrenamientoPerceptron(puertaXOR,pesos,umbral,lr)

In [332]:
df.tail(8)

       Epoch  Entrada_X1  Entrada_X2   Yd   Wi1  Wi2   Yr  Error   Wf1  Wf2
3992   999.0         0.0         0.0  0.0  0.27  0.5  0.0    0.0  0.27  0.5
3993   999.0         0.0         1.0  1.0  0.27  0.5  0.0    1.0  0.27  1.1
3994   999.0         1.0         0.0  1.0  0.27  1.1  0.0    1.0  0.87  1.1
3995   999.0         1.0         1.0  0.0  0.87  1.1  1.0   -1.0  0.27  0.5
3996  1000.0         0.0         0.0  0.0  0.27  0.5  0.0    0.0  0.27  0.5
3997  1000.0         0.0         1.0  1.0  0.27  0.5  0.0    1.0  0.27  1.1
3998  1000.0         1.0         0.0  1.0  0.27  1.1  0.0    1.0  0.87  1.1
3999  1000.0         1.0         1.0  0.0  0.87  1.1  1.0   -1.0  0.27  0.5

In [333]:
# abrir archivo CSV en modo de escritura
with open('L2P1-Perceptron.csv', mode='a', newline='') as file:
    writer = csv.writer(file)
    writer.writerow([''])
    writer.writerow(['Epoch','Entrada_X1', 'Entrada_X2','Yd','Wi1', 'Wi2','Yr','Error','Wf1', 'Wf2'])
    df.to_csv(file, header=False, index=False)